import type postgres from "postgres";

/** Idempotent ALTERs for columns added after first production deploy. */
export const PG_SCHEMA_HOTFIXES = [
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "folder_id" text`,
  `ALTER TABLE "exports" ADD COLUMN IF NOT EXISTS "resolution" text`,
  `ALTER TABLE "exports" ADD COLUMN IF NOT EXISTS "quality" text`,
  `ALTER TABLE "exports" ADD COLUMN IF NOT EXISTS "progress_percent" integer DEFAULT 0 NOT NULL`,
  `ALTER TABLE "exports" ADD COLUMN IF NOT EXISTS "progress_stage" text`,
  `ALTER TABLE "exports" ADD COLUMN IF NOT EXISTS "progress_message" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "tts_speed" real DEFAULT 1 NOT NULL`,
  `ALTER TABLE "youtube_metadata" ADD COLUMN IF NOT EXISTS "cover_avatar_id" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "script_draft" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "script_draft_notes" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "script_draft_status" text DEFAULT 'none' NOT NULL`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "script_draft_version" integer`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "tts_voice_settings" text DEFAULT '{}' NOT NULL`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "timeline_free_edit" boolean DEFAULT false NOT NULL`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "video_timeline_start" real`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "narration_timeline_start" real`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "scene_timeline_start" real`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "video_shot_count" integer DEFAULT 1 NOT NULL`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "video_camera_angle" text DEFAULT 'auto' NOT NULL`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "keyframe_fit_mode" text DEFAULT 'cover' NOT NULL`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "stock_video_id" text`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "open_router_cost_usd" real`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "keyframe_ai_model" text`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "video_ai_model" text`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "narration_ai_model" text`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "scene_audio_ai_model" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "script_language" text DEFAULT 'en' NOT NULL`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "music_start_seconds" real DEFAULT 0 NOT NULL`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "music_span_seconds" real`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "music2_url" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "music2_status" text DEFAULT 'none' NOT NULL`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "music2_prompt" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "music2_timeline_start_seconds" real`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "music2_file_start_seconds" real DEFAULT 0 NOT NULL`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "preview_mode" text DEFAULT 'auto' NOT NULL`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "video_clip_audio" text DEFAULT 'default' NOT NULL`,
  `ALTER TABLE "media_library_folders" ADD COLUMN IF NOT EXISTS "project_id" text`,
  `CREATE INDEX IF NOT EXISTS "media_library_folders_user_project" ON "media_library_folders" ("user_id", "project_id")`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "learned_notes" text`,
  `CREATE TABLE IF NOT EXISTS "script_versions" (
    "id" text PRIMARY KEY NOT NULL,
    "project_id" text NOT NULL REFERENCES "projects"("id") ON DELETE cascade,
    "version" integer NOT NULL,
    "script" text NOT NULL,
    "notes" text,
    "source" text NOT NULL,
    "summary" text,
    "word_count" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "script_versions_project_version" ON "script_versions" ("project_id", "version")`,
  `CREATE TABLE IF NOT EXISTS "media_library_folders" (
    "id" text PRIMARY KEY NOT NULL,
    "user_id" text NOT NULL,
    "parent_id" text,
    "name" text NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "media_library_assets" (
    "id" text PRIMARY KEY NOT NULL,
    "user_id" text NOT NULL,
    "folder_id" text,
    "name" text NOT NULL,
    "url" text NOT NULL,
    "mime_type" text DEFAULT 'image/jpeg' NOT NULL,
    "kind" text DEFAULT 'image' NOT NULL,
    "source" text DEFAULT 'upload' NOT NULL,
    "project_id" text,
    "block_id" text,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "media_library_assets_user_folder" ON "media_library_assets" ("user_id", "folder_id")`,
  `CREATE INDEX IF NOT EXISTS "media_library_assets_user_url" ON "media_library_assets" ("user_id", "url")`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "content_type" text DEFAULT 'video' NOT NULL`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "post_format" text DEFAULT 'carousel' NOT NULL`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "social_aspect_ratio" text DEFAULT '4:5' NOT NULL`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "post_kind" text DEFAULT 'educational' NOT NULL`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "slide_count" integer DEFAULT 7 NOT NULL`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "social_use_avatar" boolean DEFAULT false NOT NULL`,
  `CREATE TABLE IF NOT EXISTS "social_slides" (
    "id" text PRIMARY KEY NOT NULL,
    "project_id" text NOT NULL REFERENCES "projects"("id") ON DELETE cascade,
    "position" integer NOT NULL,
    "slide_role" text DEFAULT 'body' NOT NULL,
    "headline" text DEFAULT '' NOT NULL,
    "body_text" text DEFAULT '' NOT NULL,
    "visual_prompt" text DEFAULT '' NOT NULL,
    "image_url" text,
    "status" text DEFAULT 'draft' NOT NULL,
    "avatar_id" text,
    "error_message" text,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "social_metadata" (
    "id" text PRIMARY KEY NOT NULL,
    "project_id" text NOT NULL REFERENCES "projects"("id") ON DELETE cascade,
    "hook_line" text,
    "caption" text,
    "hashtags" text DEFAULT '[]' NOT NULL,
    "slide_notes" text DEFAULT '[]' NOT NULL,
    "status" text DEFAULT 'draft' NOT NULL,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "social_metadata_project_id_unique" ON "social_metadata" ("project_id")`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "genre" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "visual_style" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "voice_tone" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "color_palette" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "visual_mood" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "gallery_folder_id" text`,
  `ALTER TABLE "media_library_folders" ADD COLUMN IF NOT EXISTS "project_dna_id" text`,
  `ALTER TABLE "social_slides" ADD COLUMN IF NOT EXISTS "reference_asset_id" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "llm_model" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "image_model" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "video_model" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "video_clip_audio" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "tts_model" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "tts_voice" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "video_format" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "cut_pace" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "script_language" text`,
  `ALTER TABLE "project_dna" ADD COLUMN IF NOT EXISTS "target_duration_seconds" integer`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "scenario_id" text`,
  `ALTER TABLE "story_blocks" ADD COLUMN IF NOT EXISTS "scenario_id" text`,
  `CREATE TABLE IF NOT EXISTS "scenarios" (
    "id" text PRIMARY KEY NOT NULL,
    "user_id" text NOT NULL,
    "name" text NOT NULL,
    "description" text,
    "image_urls" text DEFAULT '[]' NOT NULL,
    "primary_image_url" text,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "variation_sets" (
    "id" text PRIMARY KEY NOT NULL,
    "user_id" text NOT NULL,
    "name" text NOT NULL,
    "source_image_url" text NOT NULL,
    "instructions" text,
    "aspect_ratio" text DEFAULT '1:1' NOT NULL,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "variation_items" (
    "id" text PRIMARY KEY NOT NULL,
    "set_id" text NOT NULL REFERENCES "variation_sets"("id") ON DELETE cascade,
    "user_id" text NOT NULL,
    "direction" text,
    "image_url" text,
    "status" text DEFAULT 'generating' NOT NULL,
    "error" text,
    "video_url" text,
    "video_status" text,
    "video_error" text,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `ALTER TABLE "variation_sets" ADD COLUMN IF NOT EXISTS "image_model" text`,
  `ALTER TABLE "variation_sets" ADD COLUMN IF NOT EXISTS "video_model" text`,
  `ALTER TABLE "variation_items" ADD COLUMN IF NOT EXISTS "image_model" text`,
  `ALTER TABLE "variation_items" ADD COLUMN IF NOT EXISTS "video_model" text`,
  `ALTER TABLE "variation_sets" ADD COLUMN IF NOT EXISTS "text_mode" text DEFAULT 'keep' NOT NULL`,
  `ALTER TABLE "variation_sets" ADD COLUMN IF NOT EXISTS "custom_text" text`,
  `ALTER TABLE "variation_items" ADD COLUMN IF NOT EXISTS "headline" text`,
  `CREATE TABLE IF NOT EXISTS "image_chats" (
    "id" text PRIMARY KEY NOT NULL,
    "user_id" text NOT NULL,
    "title" text DEFAULT 'New chat' NOT NULL,
    "image_model" text,
    "aspect_ratio" text DEFAULT '1:1' NOT NULL,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "image_chat_messages" (
    "id" text PRIMARY KEY NOT NULL,
    "chat_id" text NOT NULL REFERENCES "image_chats"("id") ON DELETE cascade,
    "user_id" text NOT NULL,
    "role" text NOT NULL,
    "content" text DEFAULT '' NOT NULL,
    "image_urls" text DEFAULT '[]' NOT NULL,
    "status" text DEFAULT 'ready' NOT NULL,
    "error" text,
    "prompt" text,
    "model" text,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "dub_target_language" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "dub_background_gain" real NOT NULL DEFAULT 0`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "dub_use_voice_clone" boolean NOT NULL DEFAULT false`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "dub_cloned_voice_id" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "dub_pipeline_stage" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "dub_pipeline_message" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "dub_pipeline_current" integer`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "dub_pipeline_total" integer`,
  `CREATE TABLE IF NOT EXISTS "dubbing_sources" (
    "id" text PRIMARY KEY NOT NULL,
    "project_id" text NOT NULL REFERENCES "projects"("id") ON DELETE cascade,
    "source_type" text NOT NULL,
    "source_url" text NOT NULL,
    "extracted_audio_url" text,
    "original_filename" text,
    "mime_type" text,
    "size_bytes" integer,
    "duration_seconds" real,
    "detected_language" text,
    "transcript_engine" text,
    "transcribed_at" timestamp,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "dubbing_sources_project_id_unique" ON "dubbing_sources" ("project_id")`,
  `CREATE TABLE IF NOT EXISTS "dubbing_segments" (
    "id" text PRIMARY KEY NOT NULL,
    "project_id" text NOT NULL REFERENCES "projects"("id") ON DELETE cascade,
    "position" integer NOT NULL,
    "start_seconds" real NOT NULL,
    "end_seconds" real NOT NULL,
    "source_text" text DEFAULT '' NOT NULL,
    "source_language" text,
    "translated_text" text DEFAULT '' NOT NULL,
    "target_language" text,
    "tts_audio_url" text,
    "tts_duration_seconds" real,
    "tts_model" text,
    "tts_voice" text,
    "stretch_ratio" real,
    "status" text DEFAULT 'pending' NOT NULL,
    "error_message" text,
    "speaker_id" text,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "dubbing_segments_project_position" ON "dubbing_segments" ("project_id", "position")`,
  `CREATE TABLE IF NOT EXISTS "dubbing_renders" (
    "id" text PRIMARY KEY NOT NULL,
    "project_id" text NOT NULL REFERENCES "projects"("id") ON DELETE cascade,
    "kind" text NOT NULL,
    "url" text NOT NULL,
    "target_language" text,
    "background_gain" real DEFAULT 0 NOT NULL,
    "duration_seconds" real,
    "size_bytes" integer,
    "created_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "dubbing_renders_project_created" ON "dubbing_renders" ("project_id", "created_at" DESC)`,
  `CREATE TABLE IF NOT EXISTS "dubbing_tracks" (
    "id" text PRIMARY KEY NOT NULL,
    "project_id" text NOT NULL REFERENCES "projects"("id") ON DELETE cascade,
    "language_id" text NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "tts_voice" text,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "dubbing_tracks_project_language" ON "dubbing_tracks" ("project_id", "language_id")`,
  `CREATE TABLE IF NOT EXISTS "dubbing_segment_locales" (
    "id" text PRIMARY KEY NOT NULL,
    "segment_id" text NOT NULL REFERENCES "dubbing_segments"("id") ON DELETE cascade,
    "track_id" text NOT NULL REFERENCES "dubbing_tracks"("id") ON DELETE cascade,
    "translated_text" text DEFAULT '' NOT NULL,
    "tts_audio_url" text,
    "tts_duration_seconds" real,
    "tts_model" text,
    "tts_voice" text,
    "stretch_ratio" real,
    "status" text DEFAULT 'pending' NOT NULL,
    "error_message" text,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "dubbing_segment_locales_segment_track" ON "dubbing_segment_locales" ("segment_id", "track_id")`,
  `CREATE INDEX IF NOT EXISTS "dubbing_segment_locales_track" ON "dubbing_segment_locales" ("track_id")`,
  `ALTER TABLE "dubbing_renders" ADD COLUMN IF NOT EXISTS "track_id" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "social_art" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "social_references" text`,
  `ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "social_reference_notes" text`,
  `ALTER TABLE "social_slides" ADD COLUMN IF NOT EXISTS "art" text`,
  `CREATE TABLE IF NOT EXISTS "social_art_brand_kits" (
    "id" text PRIMARY KEY NOT NULL,
    "user_id" text NOT NULL,
    "project_dna_id" text NOT NULL REFERENCES "project_dna"("id") ON DELETE cascade,
    "handle" text DEFAULT '' NOT NULL,
    "colors" text DEFAULT '{}' NOT NULL,
    "accent_shine" boolean DEFAULT true NOT NULL,
    "font_heading" text DEFAULT 'Montserrat' NOT NULL,
    "font_body" text DEFAULT 'Montserrat' NOT NULL,
    "uppercase_titles" boolean DEFAULT true NOT NULL,
    "decor_color" text DEFAULT '#f59e0b' NOT NULL,
    "decor_default" boolean DEFAULT false NOT NULL,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "social_art_brand_kits_project_dna_id_unique" ON "social_art_brand_kits" ("project_dna_id")`,
  `CREATE TABLE IF NOT EXISTS "creatives" (
    "id" text PRIMARY KEY NOT NULL,
    "user_id" text NOT NULL,
    "code" integer NOT NULL,
    "version" integer DEFAULT 1 NOT NULL,
    "product" text NOT NULL,
    "angle" text NOT NULL,
    "hook" text DEFAULT '' NOT NULL,
    "format" text NOT NULL,
    "creator" text DEFAULT '' NOT NULL,
    "aspect_ratio" text NOT NULL,
    "language" text DEFAULT 'PT' NOT NULL,
    "kind" text DEFAULT 'image' NOT NULL,
    "file_url" text NOT NULL,
    "thumb_url" text,
    "mime_type" text NOT NULL,
    "width" integer,
    "height" integer,
    "duration_seconds" real,
    "size_bytes" integer DEFAULT 0 NOT NULL,
    "original_name" text DEFAULT '' NOT NULL,
    "source" text DEFAULT 'upload' NOT NULL,
    "source_ref" text,
    "status" text,
    "notes" text DEFAULT '' NOT NULL,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "creatives_user_code" ON "creatives" ("user_id", "code")`,
  `CREATE TABLE IF NOT EXISTS "creative_metrics" (
    "id" text PRIMARY KEY NOT NULL,
    "user_id" text NOT NULL,
    "ad_name" text NOT NULL,
    "code" integer,
    "spend" real DEFAULT 0 NOT NULL,
    "impressions" integer DEFAULT 0 NOT NULL,
    "clicks" integer DEFAULT 0 NOT NULL,
    "results" real DEFAULT 0 NOT NULL,
    "source_file" text DEFAULT '' NOT NULL,
    "imported_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "creative_metrics_user_code" ON "creative_metrics" ("user_id", "code")`,
  `CREATE TABLE IF NOT EXISTS "creative_folders" (
    "id" text PRIMARY KEY NOT NULL,
    "user_id" text NOT NULL,
    "name" text NOT NULL,
    "created_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "creative_folders_user_name" ON "creative_folders" ("user_id", "name")`,
  `ALTER TABLE "creative_metrics" ADD COLUMN IF NOT EXISTS "import_id" text`,
  `CREATE TABLE IF NOT EXISTS "creative_metric_imports" (
    "id" text PRIMARY KEY NOT NULL,
    "user_id" text NOT NULL,
    "source_file" text DEFAULT '' NOT NULL,
    "period_start" text,
    "period_end" text,
    "rows" integer DEFAULT 0 NOT NULL,
    "matched" integer DEFAULT 0 NOT NULL,
    "imported_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "creative_metric_imports_user" ON "creative_metric_imports" ("user_id")`,
  `CREATE TABLE IF NOT EXISTS "creative_shares" (
    "id" text PRIMARY KEY NOT NULL,
    "user_id" text NOT NULL,
    "token" text NOT NULL,
    "scope" text NOT NULL,
    "scope_value" text DEFAULT '' NOT NULL,
    "expires_at" timestamp,
    "views" integer DEFAULT 0 NOT NULL,
    "last_viewed_at" timestamp,
    "created_at" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "creative_shares_token" ON "creative_shares" ("token")`,
] as const;

export async function applyPgSchemaHotfixes(client: postgres.Sql): Promise<void> {
  for (const sql of PG_SCHEMA_HOTFIXES) {
    await client.unsafe(sql);
  }
}
